# Generated by Django 5.0.6 on 2024-06-30 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('main_category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('receipts', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default=0, max_length=10)),
                ('payments', models.DecimalField(decimal_places=2, max_digits=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.company')),
            ],
        ),
    ]
