# Generated by Django 5.0.6 on 2024-06-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_transaction_approved_transaction_manager_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='manager_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
